// Lista base de motomensajería (Gran Buenos Aires), cargada una sola vez desde el CSV que pasó Diego.
// costo = lo que cobra la mensajería; el precio al cliente arranca igual y se puede editar después.
export const MOTOMENSAJERIA_INICIAL = [
  { localidad: "CABA (general)", costo: 10000, estimado: true, notas: "Tarifa por horario; bultos a consultar con la mensajería" },
  { localidad: "Adrogué", costo: 13000 },
  { localidad: "Aldo Bonzi", costo: 12000 },
  { localidad: "Alejandro Korn", costo: 61000 },
  { localidad: "Almirante Brown", costo: 13000 },
  { localidad: "Avellaneda", costo: 12000 },
  { localidad: "Banfield", costo: 13000 },
  { localidad: "Beccar (San Isidro)", costo: 12000 },
  { localidad: "Bella Vista", costo: 11000 },
  { localidad: "Benavídez", costo: 13000 },
  { localidad: "Berazategui", costo: 13000 },
  { localidad: "Bernal", costo: 13000 },
  { localidad: "Billinghurst", costo: 11000 },
  { localidad: "Bosques (Varela)", costo: 17000 },
  { localidad: "Boulogne", costo: 12000 },
  { localidad: "Burzaco", costo: 13000 },
  { localidad: "Canning", costo: 16000 },
  { localidad: "Carapachay", costo: 11000 },
  { localidad: "Caseros", costo: 10000 },
  { localidad: "Castelar", costo: 9500 },
  { localidad: "Ciudad Evita", costo: 11000 },
  { localidad: "Ciudad Jardín", costo: 10500 },
  { localidad: "Ciudadela", costo: 10500 },
  { localidad: "Claypole", costo: 13000 },
  { localidad: "Cuartel V (Moreno)", costo: 13000 },
  { localidad: "Del Viso", costo: 13000 },
  { localidad: "Derqui", costo: 13000 },
  { localidad: "Dique Luján (Tigre)", costo: 15000 },
  { localidad: "Dock Sud", costo: 12000 },
  { localidad: "Don Torcuato", costo: 12000 },
  { localidad: "El Libertador (San Martín)", costo: 13000 },
  { localidad: "El Palomar", costo: 10500 },
  { localidad: "El Pato", costo: 22000 },
  { localidad: "El Talar (Tigre)", costo: 13000 },
  { localidad: "Escobar", costo: 17000 },
  { localidad: "Esteban Echeverría", costo: 13000 },
  { localidad: "Ezeiza", costo: 13000 },
  { localidad: "Ferrari", costo: 11000 },
  { localidad: "Florencio Varela", costo: 13000 },
  { localidad: "Florida", costo: 12000 },
  { localidad: "Francisco Álvarez", costo: 12000 },
  { localidad: "Fátima (Pilar)", costo: 17000 },
  { localidad: "Garín", costo: 13000 },
  { localidad: "General Rodríguez", costo: 13000 },
  { localidad: "Gerli", costo: 12000 },
  { localidad: "Glew", costo: 27000 },
  { localidad: "González Catán", costo: 12000 },
  { localidad: "Grand Bourg", costo: 13000 },
  { localidad: "Guernica", costo: 32000 },
  { localidad: "Gutiérrez", costo: 17000 },
  { localidad: "Haedo", costo: 10000 },
  { localidad: "Hudson", costo: 17000 },
  { localidad: "Hurlingham", costo: 10000 },
  { localidad: "Ingeniero Budge", costo: 13000 },
  { localidad: "Ingeniero J. Allan", costo: 18000 },
  { localidad: "Ingeniero Maschwitz", costo: 13000, notas: "En algunas listas figura como Mascwitz" },
  { localidad: "Isidro Casanova", costo: 11000 },
  { localidad: "Ituzaingó", costo: 8000 },
  { localidad: "José C. Paz", costo: 13000 },
  { localidad: "José León Suárez", costo: 13000 },
  { localidad: "José Mármol", costo: 13000 },
  { localidad: "La Ferrere", costo: 12000 },
  { localidad: "La Plata", costo: 71000 },
  { localidad: "La Reja", costo: 12000 },
  { localidad: "Lanús", costo: 13000 },
  { localidad: "Lavallol", costo: 13000 },
  { localidad: "Libertad (Merlo)", costo: 11000 },
  { localidad: "Loma Hermosa", costo: 13000 },
  { localidad: "Lomas de Zamora", costo: 13000 },
  { localidad: "Lomas del Mirador", costo: 10500 },
  { localidad: "Longchamps", costo: 13000 },
  { localidad: "Luis Guillón", costo: 13000 },
  { localidad: "Luján", costo: 16000 },
  { localidad: "Manuel Alberti", costo: 13000 },
  { localidad: "Manzanares (Pilar)", costo: 17000 },
  { localidad: "Maquinista Savio", costo: 15000 },
  { localidad: "Marcos Paz", costo: 13000 },
  { localidad: "Mariano Acosta", costo: 11000 },
  { localidad: "Martín Coronado", costo: 11000 },
  { localidad: "Martínez", costo: 11000 },
  { localidad: "Matheu", costo: 13000 },
  { localidad: "Merlo", costo: 11000 },
  { localidad: "Monte Grande", costo: 13000 },
  { localidad: "Moreno Centro", costo: 12000 },
  { localidad: "Morón", costo: 10000 },
  { localidad: "Munro", costo: 11000 },
  { localidad: "Muñiz", costo: 11000 },
  { localidad: "Nordelta", costo: 15000 },
  { localidad: "Olivos", costo: 11000 },
  { localidad: "Opendoor", costo: 27000 },
  { localidad: "Pablo Nogués", costo: 13000 },
  { localidad: "Pablo Podestá", costo: 12000 },
  { localidad: "Pacheco", costo: 14000 },
  { localidad: "Padua", costo: 11000 },
  { localidad: "Parque San Martín", costo: 11000 },
  { localidad: "Paso del Rey", costo: 12000 },
  { localidad: "Pilar (Centro)", costo: 13000 },
  { localidad: "Polvorines", costo: 12000 },
  { localidad: "Pontevedra", costo: 11000 },
  { localidad: "Quilmes", costo: 13000 },
  { localidad: "Rafael Calzada", costo: 13000 },
  { localidad: "Rafael Castillo", costo: 11000 },
  { localidad: "Ramos Mejía", costo: 10500 },
  { localidad: "Ranelagh (Berazategui)", costo: 13000, notas: "En algunas listas figura como Ranelagh Bera" },
  { localidad: "Rincón de Milberg", costo: 13000 },
  { localidad: "San Andrés (San Martín)", costo: 11000 },
  { localidad: "San Fernando", costo: 13000 },
  { localidad: "San Francisco Solano", costo: 13000 },
  { localidad: "San Isidro", costo: 12000 },
  { localidad: "San Justo", costo: 11000 },
  { localidad: "San Martín", costo: 11000 },
  { localidad: "San Miguel (Centro)", costo: 11000 },
  { localidad: "San Vicente", costo: 61000 },
  { localidad: "Santa Rosa", costo: 17000 },
  { localidad: "Santos Lugares", costo: 11000 },
  { localidad: "Sarandí", costo: 12000 },
  { localidad: "Spegazzini", costo: 16000 },
  { localidad: "Sáenz Peña", costo: 11000 },
  { localidad: "Tablada", costo: 11500 },
  { localidad: "Tapiales", costo: 10500 },
  { localidad: "Temperley", costo: 13000 },
  { localidad: "Tigre (Centro)", costo: 13000 },
  { localidad: "Tortuguitas", costo: 13000 },
  { localidad: "Tristán Suárez", costo: 13000 },
  { localidad: "Trujui", costo: 12000 },
  { localidad: "Valentín Alsina", costo: 12000 },
  { localidad: "Vicente López", costo: 11000 },
  { localidad: "Victoria", costo: 13000 },
  { localidad: "Villa Adelina", costo: 11000 },
  { localidad: "Villa Ballester", costo: 11000 },
  { localidad: "Villa Bosch", costo: 10500 },
  { localidad: "Villa Celina", costo: 13000 },
  { localidad: "Villa Centenario", costo: 13000 },
  { localidad: "Villa de Mayo", costo: 13000 },
  { localidad: "Villa Insuperable", costo: 10500 },
  { localidad: "Villa Lugano", costo: 10000, notas: "Barrio de CABA con precio propio (no usa la tarifa general de CABA)" },
  { localidad: "Villa Luzuriaga", costo: 11000 },
  { localidad: "Villa Madero", costo: 10500 },
  { localidad: "Villa Martelli", costo: 11000 },
  { localidad: "Villa Riachuelo", costo: 11000, notas: "Barrio de CABA con precio propio (no usa la tarifa general de CABA)" },
  { localidad: "Villa Rosa", costo: 13000 },
  { localidad: "Villa San Luis", costo: 17000 },
  { localidad: "Villa Sarmiento", costo: 10000 },
  { localidad: "Villa Tesei", costo: 10000 },
  { localidad: "Villa Vatteone", costo: 17000 },
  { localidad: "Virrey del Pino", costo: 15000 },
  { localidad: "Virreyes", costo: 13000 },
  { localidad: "Wilde", costo: 12000 },
  { localidad: "Williams Morris", costo: 10000 },
  { localidad: "Zeballos", costo: 17000 },
  { localidad: "Zelaya (Pilar)", costo: 18000 },
  { localidad: "Zárate", costo: 61000 },
];
